//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moments.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Node
    {
        public long Id { get; set; }
        public long ParentId { get; set; }
        public string Type { get; set; }
        public string Contents { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool Active { get; set; }
        public int CreatedBy { get; set; }
        public int StoryId { get; set; }
    
        public virtual Story Story { get; set; }
    }
}
