//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moments.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionEmail
    {
        public int Id { get; set; }
        public string UserFullName { get; set; }
        public string Email { get; set; }
        public string Message { get; set; }
        public Nullable<int> InvitedBy { get; set; }
        public Nullable<int> AllowedInvitations { get; set; }
        public string AuthToken { get; set; }
        public string RegistrationLink { get; set; }
        public string CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
