//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moments.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoriesNode
    {
        public int Id { get; set; }
        public Nullable<int> StoryId { get; set; }
        public string LayerType { get; set; }
        public string Path { get; set; }
        public string SourceId { get; set; }
        public string DestinationId { get; set; }
        public string Text { get; set; }
        public string xAxis { get; set; }
        public string yAxis { get; set; }
        public string zIndex { get; set; }
        public Nullable<int> Priority { get; set; }
        public string HtmlId { get; set; }
        public string Type { get; set; }
        public Nullable<int> UserProfileId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual Story Story { get; set; }
    }
}
