//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moments.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserProfile()
        {
            this.PromotionEmails = new HashSet<PromotionEmail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> UserRegistrationId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PhoneNo { get; set; }
        public string MobileNo { get; set; }
        public string DOB { get; set; }
        public string Gender { get; set; }
        public string PrimaryAddress { get; set; }
        public string SecondryAddress { get; set; }
        public string CNIC { get; set; }
        public string Status { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsFeatured { get; set; }
        public bool IsBlocked { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PromotionEmail> PromotionEmails { get; set; }
        public virtual UserRegistration UserRegistration { get; set; }
    }
}
